-- =====================================================
-- Coffee Sales Trend Analysis | SQL Business Questions
-- =====================================================

-- Question 1: Calculate the Total Revenue Generated by the Coffee Shop

SELECT ROUND(SUM(`money(Rs)`), 2) AS total_revenue
FROM coffee_data;


-- Question 2: Calculate the Total Number of Orders

SELECT COUNT(*) AS total_orders
FROM coffee_data;


-- Question 3: Identify Revenue Generated by Each Coffee Product

SELECT
    coffee_name,
    ROUND(SUM(`money(Rs)`), 2) AS revenue
FROM coffee_data
GROUP BY coffee_name
ORDER BY revenue DESC;


-- Question 4: Determine the Most Frequently Ordered Coffee Products

SELECT
    coffee_name,
    COUNT(*) AS total_orders
FROM coffee_data
GROUP BY coffee_name
ORDER BY total_orders DESC;


-- Question 5: Analyze Revenue by Payment Method

SELECT
    cash_type,
    ROUND(SUM(`money(Rs)`), 2) AS revenue
FROM coffee_data
GROUP BY cash_type;


-- Question 6: Identify the Highest Revenue-Generating Day of the Week

SELECT
    Weekday,
    ROUND(SUM(`money(Rs)`), 2) AS revenue
FROM coffee_data
GROUP BY Weekday
ORDER BY revenue DESC
LIMIT 1;


-- Question 7: Analyze Revenue Distribution Across Weekdays

SELECT
    Weekday,
    ROUND(SUM(`money(Rs)`), 2) AS revenue
FROM coffee_data
GROUP BY Weekday
ORDER BY revenue DESC;


-- Question 8: Analyze Monthly Revenue Trends

SELECT
    Month_name,
    ROUND(SUM(`money(Rs)`), 2) AS revenue
FROM coffee_data
GROUP BY Month_name, Monthsort
ORDER BY Monthsort;


-- Question 9: Identify Peak Ordering Hours

SELECT
    hour_of_day,
    COUNT(*) AS total_orders
FROM coffee_data
GROUP BY hour_of_day
ORDER BY total_orders DESC;


-- Question 10: Identify the Most Popular Coffee Products During Morning Hours

SELECT
    coffee_name,
    COUNT(*) AS total_orders
FROM coffee_data
WHERE Time_of_Day = 'Morning'
GROUP BY coffee_name
ORDER BY total_orders DESC;


-- Question 11: Identify the Most Popular Coffee Products During Afternoon Hours

SELECT
    coffee_name,
    COUNT(*) AS total_orders
FROM coffee_data
WHERE Time_of_Day = 'Afternoon'
GROUP BY coffee_name
ORDER BY total_orders DESC;


-- Question 12: Identify the Most Popular Coffee Products During Night Hours

SELECT
    coffee_name,
    COUNT(*) AS total_orders
FROM coffee_data
WHERE Time_of_Day = 'Night'
GROUP BY coffee_name
ORDER BY total_orders DESC;
